[project]
name = "curious-uv"
version = "0.1.0"
description = "궁금하지?"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.12.2",
    "google-genai>=1.35.0",
    "python-dotenv>=1.1.1",
]
